-- Create Building Queue Table
CREATE TABLE IF NOT EXISTS public.building_queue (
    id bigint generated by default as identity primary key,
    planet_id uuid not null references public.planets(id) on delete cascade,
    building_id integer not null,
    target_level integer not null,
    start_time timestamptz not null,
    end_time timestamptz not null,
    created_at timestamptz default now(),
    
    constraint building_queue_check check (target_level > 0)
);

-- Create Index for fast lookup of active construction
CREATE INDEX idx_building_queue_planet ON public.building_queue(planet_id);
CREATE INDEX idx_building_queue_end_time ON public.building_queue(end_time);

-- Create Shipyard Queue Table
CREATE TABLE IF NOT EXISTS public.shipyard_queue (
    id bigint generated by default as identity primary key,
    planet_id uuid not null references public.planets(id) on delete cascade,
    unit_id integer not null,
    quantity integer not null,
    start_time timestamptz not null,
    end_time timestamptz not null, -- Time when the ENTIRE batch finishes? Or next unit?
    -- OGame usually processes unit by unit linearly.
    -- Better approach: One row per "Order". 
    -- We can store "finished_quantity" if we want partial updates.
    processed_quantity integer default 0,
    created_at timestamptz default now(),

    constraint shipyard_queue_quantity_check check (quantity > 0)
);

CREATE INDEX idx_shipyard_queue_planet ON public.shipyard_queue(planet_id);
CREATE INDEX idx_shipyard_queue_end_time ON public.shipyard_queue(end_time);

-- Add comments
COMMENT ON TABLE public.building_queue IS 'Active construction jobs for buildings';
COMMENT ON TABLE public.shipyard_queue IS 'Active construction jobs for shipyard units';
